### ISSUE TITLE
Live demo

### ISSUE THREAD

**Issue by rohmanhm** [thk2b/autoscroll-react#12]
Hi, Nice package.
But I think it will helpful for beginners if you provide a live demo to test it out.

**Comment by thk2b** [comment]
Sure thing. I wrote a quick demo app available under `/demo` but it requires cloning and starting a dev server which is not convenient.

I think It could be hosted using github pages. I'll look into it.

**Comment by rohmanhm** [comment]
Great!
Some people do not have time for cloning and run the demo on their own machine.

**Comment by thk2b** [comment]
Here is a demo I just created. https://codesandbox.io/s/0315qvkx20

**Comment by thk2b** [comment]
Thanks for the input, and feel free to let me know if anything in the demo is unclear.
